### ISSUE TITLE
Since Corec f [] is uninhabitable why do match and match' exist?

### ISSUE THREAD

**Issue by janpath** [VinylRecords/Vinyl#105]
```haskell
-- | Pattern match on a CoRec by specifying handlers for each case. If the
-- CoRec is non-empty this function is total. Note that the order of the
-- Handlers has to match the type level list (t:ts).
--
-- ...
--
match      :: RecApplicative (t ': ts)
           => CoRec Identity (t ': ts) -> Handlers (t ': ts) b -> b

-- | Pattern match on a CoRec by specifying handlers for each case. The only case
-- in which this can produce a Nothing is if the list ts is empty.
match'      :: RecApplicative ts => CoRec Identity ts -> Handlers ts b -> Maybe b
```

Since `Corec f []` is uninhabitable it should be possible to generalize `match` to `RecApplicative ts => CoRec Identity ts -> Handlers ts b -> b` without loosing totality. Then you could also do away with `match'` (or keep it for compatility reasons). If I am missing something it would be nice if that would be documented.

**Comment by acowley** [comment]
Huh, I think you're right. Pinging @noinia who I believe wrote this originally for `Frames`.

**Comment by janpath** [comment]
Here is an alternative implementation of `match`. It also does away with the `RecApplicative` constraint.

```haskell
match :: CoRec Identity ts -> Handlers ts b -> b
match (CoRec (Identity t)) hs = case rget Proxy hs of H f -> f t
```

**Comment by noinia** [comment]
Ah, good observation. I can't remember exactly if I had other concerns in mind when writing this initially, but I think I may just missed that `Corec f []` is uninhabitable. So simplifying it looks good to me, and if we can get rid of the RecApplicative all the better.

**Comment by acowley** [comment]
@janpath can you open a PR to keep the ball rolling to fixing this?
