### ISSUE TITLE
Non-constant access time to record fields?

### ISSUE THREAD

**Issue by schernichkin** [VinylRecords/Vinyl#108]
During testing performance of various record libraries I've discovered that field access time depends on the field position in the record. In my tests it varies from 3 ns (for the first field) to 20 ns for 16-th. You can find performance tests and report here https://github.com/schernichkin/Vinyl

If it's really true, I think this behavior should be mentioned in the library documentation. I't also would be nice to have an explanation of this behavior, because the reason performance degradation is not quite oblivious.

**Comment by acowley** [comment]
Thank you for taking a look at this! Would it okay with you if we pulled your `AccessorsBench` into this repository? I think it would provide a very helpful grounding for the needed discussion about performance.

**Comment by acowley** [comment]
I've added a new `ARec` type that seeks to extend constant-time field access to more types. The [arec branch](https://github.com/VinylRecords/Vinyl/tree/arec) includes an updated README, and an update of the benchmark you provided to demonstrate its use.
