### ISSUE TITLE
Misleading benchmark results

### ISSUE THREAD

**Issue by larskuhtz** [VinylRecords/Vinyl#110]
[These benchmarks](https://github.com/VinylRecords/Vinyl/blob/a5ffd10fbc747c5366ae9806e61bf45f78c3eb33/benchmarks/AccessorsBench.hs#L58) may be misleading. When I add benchmark groups

```hs
       bgroup "FieldRec IO"
         [ bench "a0" $ nfIO $ (fmap (rvalf #a0)) (return newF)
         , bench "a4" $ nfIO $ (fmap (rvalf #a4)) (return newF)
         , bench "a8" $ nfIO $ (fmap (rvalf #a8)) (return newF)
         , bench "a12" $ nfIO $ (fmap (rvalf #a12)) (return newF)
         , bench "a15"  $ nfIO $ (fmap (rvalf #a15)) (return newF)
         ]
```

and

```hs
       , bgroup "AFieldRec IO"
         [ bench "a0" $ nfIO $ (fmap (rvalf #a0)) (return arec)
         , bench "a4" $ nfIO $ (fmap (rvalf #a4)) (return arec)
         , bench "a8" $ nfIO $ (fmap (rvalf #a8)) (return arec)
         , bench "a12" $ nfIO $ (fmap (rvalf #a12)) (return arec)
         , bench "a15"  $ nfIO $ (fmap (rvalf #a15)) (return arec)
         ]
```

I get the following results

<img width="908" alt="screen shot 2018-02-21 at 9 26 08 am" src="https://user-images.githubusercontent.com/1369810/36495191-5ac66148-16e9-11e8-9be1-c7dfe59d6979.png">

which seems to indicate that either `nfIO` doesn't fully force the results these benchmark or that `nf` and `nfIO` benchmarks are generally not comparable. 

My guess is that the difference here is due to GHC optimizing the computations in `IO` more aggressively. However, the purpose of the benchmarks doesn't seem to be to compare performance in different evaluation contexts but access performance with respect to different data layouts.

**Comment by acowley** [comment]
Yes, the `nfIO` results are almost certainly wrong / unhelpful. I'll remove them as soon as I get a chance. I have some follow-up work that will provide a better look at performance, but it's taken me longer than I had hoped to get it ready.

**Comment by acowley** [comment]
Done. Thank you for the nudge to fix this!
