### ISSUE TITLE
ElField missing instances

### ISSUE THREAD

**Issue by bmabsout** [VinylRecords/Vinyl#121]
Any reason why instances for ElField like these don't exist?

```haskell
instance Semigroup b => Semigroup (ElField '(a,b)) where
  Field x <> Field y = Field (x <> y)

instance (KnownSymbol a, Monoid b) => Monoid (ElField '(a,b)) where
  mempty = Field mempty
```

**Comment by acowley** [comment]
Not that I can think of! Do you want to PR them or should I add them? If you’re using `vinyl`, I’d be quite interested if you could try the `master` branch to be sure it works for you. I’d like to push that major bump soon, so I’ll roll this change into that.

**Comment by bmabsout** [comment]
Woops sorry, I tried adding it to master and found out that the instance already exists in `Data.Vinyl.Functor` but not on the latest version on hackage.
