### ISSUE TITLE
Build CoRec ElField value

### ISSUE THREAD

**Issue by vdorr** [VinylRecords/Vinyl#127]
Using ElField as CoRec functor and field value type is not fully known, ghc ends with "Ambiguous type" error, even when field name is unique. As in this example:

value :: CoRec ElField '[ '("a", Int) ]
value = CoRec (#a =: 1)

I need in my use-case ghc to infer fairly long type, so i'd like to make this work using unique labels, how i can do it with ElField? Or possibly user type while keeping rest of vinyl's CoRec machinery.

**Comment by acowley** [comment]
Sorry that commit closed this a bit eagerly. Does the [`corec`](https://github.com/VinylRecords/Vinyl/blob/master/Data/Vinyl/CoRec.hs#L34) function help you out? If not, please re-open and we'll take another crack at it.

**Comment by vdorr** [comment]
It works perfectly. Thank you!
