### ISSUE TITLE
Show instance

### ISSUE THREAD

**Issue by acowley** [VinylRecords/Vinyl#69]
I hate asking this, but could we print records with comma separators rather than semicolons? I think commas are more common for this purpose, they also are more similar to the way a list would print (so that the curly braces distinguish our HList from a regular list), and, this is what's rubbing me the wrong way right now, we have to use a leading colon for type operators. I find that a printed record is too busy visually with semicolon field separators combined with colon-prefixed type operators. Commas just look nicer to me.

This is almost entirely a subjective thing, so if you feel like semicolons really are the right way, feel free to disagree without having to offer any kind of argument as the room for debate on an aesthetic issue like this is either infinite or zero.

**Comment by jonsterling** [comment]
Fine by me!
JMS

**Comment by jonsterling** [comment]
I bet this was the last thing you needed before you could use Vinyl for Frames? :wink:
