### ISSUE TITLE
Give `:&` a lower fixity

### ISSUE THREAD

**Issue by andrewthad** [VinylRecords/Vinyl#71]
Something like `infixr 7` would be good (it's at 9 right now). It would be nice to give other operators a chance to bind more tightly so that we could do this:

    jon = SName =:: "jon"
       :& SAge =:: 23
       :& SSleeping =:: False
       :& RNil

instead of this:

    jon = (SName =:: "jon")
       :& (SAge =:: 23)
       :& (SSleeping =:: False)
       :& RNil

Example taken from the tutorial.

**Comment by jonsterling** [comment]
That sounds reasonable to me. @acowley what do you think?

**Comment by acowley** [comment]
👍

**Comment by joneshf** [comment]
I was just coming here to suggest this! PR incoming.

**Comment by jonsterling** [comment]
Resolved by #73
