### ISSUE TITLE
OverloadedLists?

### ISSUE THREAD

**Issue by joneshf** [VinylRecords/Vinyl#74]
Is it possible to use the `OverloadedLists` extension for `Rec`? I'm not sure if it's been discussed or not, but I didn't see anything about it. Just seems like a little additional sugar that might be nice to have.

**Comment by jonsterling** [comment]
We'd love to use `OverloadedLists`, but it is not yet possible to do so. I believe that @cartazio had a proposal at one point to generalize `OverloadedLists` such that it could be used for heterogeneous list structures like Vinyl, though.

**Comment by joneshf** [comment]
I see, looking forward to what comes of that.
