### ISSUE TITLE
Identity, Compose, and Const

### ISSUE THREAD

**Issue by andrewthad** [VinylRecords/Vinyl#82]
This has been brought up before, but I figured that it's worth bringing up again since there have been some changes in the haskell ecosystem since last time. Two things have happened that I think it's worth `vinyl` considering:

1. `Data.Functor.Identity` has move from `transformers` to `base` (I think this happened in `base-4.8`). I think that the `Show` instance for the `Identity` in `base` differs from the one in `vinyl`. Also, depending on this causes incompatibility with GHC < 7.10.
2. The `Compose` and `Constant` types from `transformers-5.0` are now polykinded. This is a very new change, so depending on these would be terrible at this point in time. One cool thing is that they have way more instances written for them than the versions of these data types in `vinyl`.

I'm not proposing changing anything at the moment, but I would like to add an explanation of this situation to the haddocks for `Data.Vinyl.Functor`. @acowley Does that sound good to you?

**Comment by acowley** [comment]
Yes, any improvements to the documentation of those bits is welcome. They're kind of idiosyncratic, but things like the long-missing `Show` instance for `Identity` were better addressed by including those types here.

**Comment by andrewthad** [comment]
Added some examples and a little background on the data types.

**Comment by jonsterling** [comment]
I don't intend to have any say in Vinyl-land, but I would just make a few notes:

- If things are in `base` and are polykinded, I say use them!
- You probably want to keep the custom `Identity` around in order to get a silent `Show` instance.
- If we have not already depended on `transformers`, I recommend not adding it!

**Comment by andrewthad** [comment]
I agree with all three of your points.
