### ISSUE TITLE
Tutorial is difficult to find

### ISSUE THREAD

**Issue by andrewthad** [VinylRecords/Vinyl#84]
I just learned on reddit that there is [at least one person out there](https://www.reddit.com/r/haskell/comments/46pjmm/the_joy_and_agony_of_haskell_in_production/d076sxi) who couldn't find the tutorial. I'd be happy to make a `Vinyl.Tutorial` module (in the spirit of `Pipes.Tutorial`) that has the same information copied into it and formatted for haddocks. @acowley Do you find this agreeable, or is there another place you think would be better?

**Comment by acowley** [comment]
That would be great! The existing tutorial has been brought through every generation of the library, so it's not exactly tuned for any particular version. If you have ideas for improving it, please do so.

**Comment by andrewthad** [comment]
I've put up a PR for this. I actually feel like the example is pretty good as is, so I left it alone for except for the moving a few things around so that doctest would accept it.

**Comment by acowley** [comment]
Thanks for doing this, Andrew!
