### ISSUE TITLE
Setting all the fields but one to the Default value

### ISSUE THREAD

**Issue by meditans** [VinylRecords/Vinyl#86]
Hi,

this is a question on vinyl usage, posted here because I didn't find a more suitable place.

The problem is the following: following `vinyl` tutorial, I have a promoted type meant to tag the fields of the record, and an interpretation type family `Attr` mapping it to concrete types of my choice. Let's say the promoted type is:

```haskell
data Tag = Foo1 | Foo2 | Foo3 | Bar
```

I also happen to have a `Default` instance for `Attr Foo1` to `Attr Foo3`, but I don't have it for `Attr Bar`.

I'd like to write a function, `bar1`, which takes no parameters, and sets the `Bar` value in the record to a specified constant, while putting the other fields to their `Default` value.

So, I'd like the signature to be along the lines of:

```haskell
bar1 :: (RecAll Attr (rs `Excluding` 'Bar) Default, 'Bar ∈ rs) => Rec Attr rs
```

where `Excluding` could be defined as:

```haskell
type family Excluding (as :: [k]) (a :: k) :: [k] where
  Excluding '[] a       = '[]
  Excluding (a ': as) a =      Excluding as a
  Excluding (b ': as) a = b ': Excluding as a
```

Unfortunately, I've not been able to write the definition of the function. Could you give me some hints on how to do that?

**Comment by andrewthad** [comment]
You should try to avoid the `Excluding` type family. Since you have an overlapped pattern where you check for type equality, it's tough to prove things with it. Definitely the easiest way to solve this is by just adding a `Default` instance for `Attr 'Bar`. Since it sounds like you can't do that, this is what I would recommend:

    bar1 :: (RecAll Attr rs Default) => Rec Attr ('Bar ': rs)

Just stick it on the front. You can always just `rcast` afterwards if you need a different ordering.

**Comment by meditans** [comment]
@andrewthad ok, I'll try to implement this. In the meantime, could you show how to do a proper Default instance? Like in:

    instance (RecAll f rs Default) => Default (Rec f rs) where
      def = ?

I read the sources, particularly the `mempty` function, but I'd like to avoid the proxy. Is there a way to do that?

If there isn't, does that mean that my `bar1` function will have to take a proxy parameter?

**Comment by acowley** [comment]
This may not be exactly what you want, but there's some related [sample code](https://github.com/acowley/Frames/blob/master/demo/MissingData.hs) in `Frames`.

**Comment by andrewthad** [comment]
From the source of `Data.Vinyl.Core`, we have:

    instance Monoid (Rec f '[]) where
      mempty = RNil
      RNil `mappend` RNil = RNil

    instance (Monoid (f r), Monoid (Rec f rs)) => Monoid (Rec f (r ': rs)) where
      mempty = mempty :& mempty
      (x :& xs) `mappend` (y :& ys) = (x <> y) :& (xs <> ys)

We can write `Default` the same way:

    instance Default (Rec f '[]) where
      def = RNil

    instance (Default (f r), Default (Rec f rs)) => Default (Rec f (r ': rs)) where
      def = def :& def

**Comment by andrewthad** [comment]
But if you want to have `RecAll f rs Default` as the constraint instead of `Default (Rec f rs)`, then yes, you have to add a proxy argument.

**Comment by andrewthad** [comment]
Alternatively you can have `(RecAll f rs Default, RecApplicative rs)`, and then the proxy argument can be created implicitly with `rpure Proxy`.

**Comment by meditans** [comment]
@andrewthad  ok, regarding the `bar1` problem, it suffices to write:

    bar1 :: (Default (Attr r), Default (Rec Attr rs)) => Rec Attr ('Bar ': r ': rs)
    bar1 = (SBar =:: barStar) :& def

after I defined the default instances above. Could you show more explicitly how to write the `Default` instance using `RecAll` and `RecApplicative`? I got stuck because I cannot assume the record to be in the form `(_ :& _)`

**Comment by andrewthad** [comment]
You can write:

    recDef :: RecAll f rs Default => Rec proxy rs -> Rec f rs
    recDef RNil = RNil
    recDef (_ :& rs) = def :& recDef rs

    instance (RecAll f rs Default, RecApplicative rs) => Default (Rec f rs) where
      def = recDef (rpure Proxy)

I haven't checked that, and I don't recommend that approach, but it should also work.

**Comment by andrewthad** [comment]
Also, in the example of `bar1` you gave above, you wrote:

    bar1 :: (Default (Attr r), Default (Rec Attr rs)) => Rec Attr ('Bar ': r ': rs)
    bar1 = (SBar =:: barStar) :& def

But you should have been able to write:

    bar1 :: (Default (Rec Attr rs)) => Rec Attr ('Bar ': rs)
    bar1 = (SBar =:: barStar) :& def

**Comment by meditans** [comment]
@andrewthad no, this entire question stemmed from the fact that I cannot write:

    bar1 :: (Default (Rec Attr rs)) => Rec Attr ('Bar ': rs)
    bar1 = (SBar =:: barStar) :& def

which was my previous idea (I also don't understand why, since the two formulations should contain the same information). I also wrote the alternate default definition, what I missed was the link between the two, that you suggested.

Do you have any idea on why, when I try to write the second form, I get the error:

    src/Lib.hs:88:28: Could not deduce (Default (Rec Attr rs)) …
          arising from a use of ‘def’
        from the context (RecAll Attr rs Default)
          bound by the type signature for
                     c :: RecAll Attr rs Default => Rec Attr ('PitchValue : rs)
          at /home/carlo/code/haskell/prova/musicRecord/src/Lib.hs:87:24-80
        In the second argument of ‘(:&)’, namely ‘def’
        In the expression: (SPitchValue =:: C) :& def
        In an equation for ‘c’: c = (SPitchValue =:: C) :& def
    src/Lib.hs:89:28: Could not deduce (Default (Rec Attr rs)) …
          arising from a use of ‘def’
        from the context (RecAll Attr rs Default)
          bound by the type signature for
                     d :: RecAll Attr rs Default => Rec Attr ('PitchValue : rs)
          at /home/carlo/code/haskell/prova/musicRecord/src/Lib.hs:87:24-80
        In the second argument of ‘(:&)’, namely ‘def’
        In the expression: (SPitchValue =:: D) :& def
        In an equation for ‘d’: d = (SPitchValue =:: D) :& def
    src/Lib.hs:90:28: Could not deduce (Default (Rec Attr rs)) …
          arising from a use of ‘def’
        from the context (RecAll Attr rs Default)
          bound by the type signature for
                     e :: RecAll Attr rs Default => Rec Attr ('PitchValue : rs)
          at /home/carlo/code/haskell/prova/musicRecord/src/Lib.hs:87:24-80
        In the second argument of ‘(:&)’, namely ‘def’
        In the expression: (SPitchValue =:: E) :& def
        In an equation for ‘e’: e = (SPitchValue =:: E) :& def
    src/Lib.hs:91:28: Could not deduce (Default (Rec Attr rs)) …
          arising from a use of ‘def’
        from the context (RecAll Attr rs Default)
          bound by the type signature for
                     f :: RecAll Attr rs Default => Rec Attr ('PitchValue : rs)
          at /home/carlo/code/haskell/prova/musicRecord/src/Lib.hs:87:24-80
        In the second argument of ‘(:&)’, namely ‘def’
        In the expression: (SPitchValue =:: F) :& def
        In an equation for ‘f’: f = (SPitchValue =:: F) :& def
    src/Lib.hs:92:28: Could not deduce (Default (Rec Attr rs)) …
          arising from a use of ‘def’
        from the context (RecAll Attr rs Default)
          bound by the type signature for
                     g :: RecAll Attr rs Default => Rec Attr ('PitchValue : rs)
          at /home/carlo/code/haskell/prova/musicRecord/src/Lib.hs:87:24-80
        In the second argument of ‘(:&)’, namely ‘def’
        In the expression: (SPitchValue =:: G) :& def
        In an equation for ‘g’: g = (SPitchValue =:: G) :& def
    src/Lib.hs:93:28: Could not deduce (Default (Rec Attr rs)) …
          arising from a use of ‘def’
        from the context (RecAll Attr rs Default)
          bound by the type signature for
                     a :: RecAll Attr rs Default => Rec Attr ('PitchValue : rs)
          at /home/carlo/code/haskell/prova/musicRecord/src/Lib.hs:87:24-80
        In the second argument of ‘(:&)’, namely ‘def’
        In the expression: (SPitchValue =:: A) :& def
        In an equation for ‘a’: a = (SPitchValue =:: A) :& def
    src/Lib.hs:94:28: Could not deduce (Default (Rec Attr rs)) …
          arising from a use of ‘def’
        from the context (RecAll Attr rs Default)
          bound by the type signature for
                     b :: RecAll Attr rs Default => Rec Attr ('PitchValue : rs)
          at /home/carlo/code/haskell/prova/musicRecord/src/Lib.hs:87:24-80
        In the second argument of ‘(:&)’, namely ‘def’
        In the expression: (SPitchValue =:: B) :& def
        In an equation for ‘b’: b = (SPitchValue =:: B) :& def
    Compilation failed.

**Comment by andrewthad** [comment]
Every one of those errors are at the call site of def. Since I can't see that part of your code, I can't figure out why it doesn't work. Can you put your project on github so I can see the source and try compiling it?

**Comment by meditans** [comment]
Sorry, I'll edit the error message before, I made some confusion when pasting, anyway the file I'm using is [here](https://gist.github.com/8d4de201672e9c2265a6). I'll put the entire stack project on github in a minute.

**Comment by meditans** [comment]
Ok, you can find the project [here](https://github.com/meditans/musicRecord), the only relevant file is `src/Lib.hs`

**Comment by andrewthad** [comment]
On this line: https://github.com/andrewthad/musicRecord/blob/52b5cd828c028807e84b795f4d5c67622bb32087/src/Lib.hs#L87

Change the constraint to `Default (Rec Attr rs)`, and it will compile.

**Comment by meditans** [comment]
@andrewthad thanks for all the help. What should I read to familiarize myself with the techniques of type level programming, like the `RecApplicative` trick that you used before, or how to actually write something like:

    c :: (rs ~ Excluding ss 'PitchValue, Default (Rec Attr rs), ('PitchValue ': rs) ≅ ss) => Rec Attr ss
    c = rcast (((SPitchValue =:: C) :& def) :: Rec Attr ('PitchValue ': rs)) :: Rec Attr ss

(it's certainly hideous, but I'd like a more thorough understanding on how to work with this type of objects, and get a better sense of the possibilities).

**Comment by andrewthad** [comment]
The most helpful explanation of doing dependent typing in haskell I've read is the [Hasochism paper](https://personal.cis.strath.ac.uk/conor.mcbride/pub/hasochism.pdf). But, it only makes sense if you already understand how to manipulate proofs with dependent typing. So, you can look at examples in agda and idris of how to model proofs as data types, and then the Hasochism paper helps you backport this knowledge to haskell. But honestly, a lot of it is just practice. The more you use GHC's type-level features, the more you see patterns emerge.

**Comment by andrewthad** [comment]
I think this can be closed.

**Comment by acowley** [comment]
Thanks @andrewthad!
