### ISSUE TITLE
What does El mean?

### ISSUE THREAD

**Issue by louispan** [VinylRecords/Vinyl#92]
My googling hasn't been able to find out what does 'El' means.
Eg 'ElField' in https://github.com/VinylRecords/Vinyl/blob/524a89c1644067c9def969a9565aa5076004a65b/Data/Vinyl/Derived.hs#L18

and Elf in https://github.com/VinylRecords/Vinyl/blob/524a89c1644067c9def969a9565aa5076004a65b/tests/Intro.lhs#L47

**Comment by acowley** [comment]
In those uses, `El` is short for `Element` as in having records that may or may not contain these fields as elements.

**Comment by louispan** [comment]
That makes sense. Thanks for answering so quickly!

**Comment by jonsterling** [comment]
@acowley Oh, I thought you knew! `El` actually refers in this case to head of the Canaanite pantheon, the father of `Yahweh`…

**Comment by acowley** [comment]
Oh, neat! Are you going to add this meaning explanation of Vinyl to the wiki?
