### ISSUE TITLE
How about rfold

### ISSUE THREAD

**Issue by andrewthad** [VinylRecords/Vinyl#97]
I can PR this if others find it agreeable:

    rfold :: Monoid m => (forall x. f x -> m) -> Rec f rs -> m

I needed this recently, and it might be appropriate for `Data.Vinyl.Core`.

**Comment by acowley** [comment]
Yes, please!

**Comment by andrewthad** [comment]
PR is up: https://github.com/VinylRecords/Vinyl/pull/98
